name: python-RETaiL
channels: 
  - conda-forge
dependencies:
  - python == 3.9
  - pip == 21.0.1
  - numpy == 1..23.5
  - pandas == 1.5.2
  - matplotlib == 3.3.4
  - scikit-learn == 1.2.1
  - seaborn == 0.12.2
  - Ipython == 7.22.0
  - ipywidgets == 7.6.3
  - scipy == 1.8.0
  - mlxtend
  - pip:
    - efficient-apriori
